### ISSUE TITLE
App crashes when there is no internet connection

### ISSUE THREAD

**Issue by Jivings** [Countly/countly-sdk-nodejs#6]
There's no error handling around the `http.request` functionality, so any connection error causes an uncaught exception.

```
Wed, 12 Sep 2018 11:52:27 GMT uncaughtException: getaddrinfo ENOTFOUND analytics.squarecat.io analytics.squarecat.io:443
Error: getaddrinfo ENOTFOUND analytics.squarecat.io analytics.squarecat.io:443
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
Wed, 12 Sep 2018 11:52:27 GMT uncaughtException: socket hang up
Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at TLSSocket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at TLSSocket.emit (events.js:211:7)
    at _handle.close (net.js:554:12)
    at TCP.done [as _onclose] (_tls_wrap.js:356:7)
```

This causes the node app to crash.

**Comment by ar2rsawseen** [comment]
Hello,
I think this should address it:
https://github.com/Countly/countly-sdk-nodejs/pull/7

Let us know if you still have any problems
